# Nom del nostre robot, el veuràs a la pestanya "Actions" de GitHub
name: Actualitzar Pàgina Web

# Això defineix com s'activa el robot.
# "workflow_dispatch" vol dir que l'activarem manualment prement un botó.
on:
  workflow_dispatch:
    # Aquí definim els camps que ens demanarà el formulari
    inputs:
      nou_contingut_html:
        description: 'Enganxa aquí el contingut complet del nou index.html'
        required: true
        type: string

jobs:
  # Aquesta és la llista de tasques que farà el robot
  actualitzar-fitxer:
    # Li diem que treballi en un ordinador virtual amb Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Pas 1: Descarregar una còpia del teu codi des de GitHub
      - name: Clonar el repositori
        uses: actions/checkout@v4

      # Pas 2: Agafar el text que li has donat i sobreescriure l'arxiu index.html
      - name: Sobreescriure index.html
        run: echo "${{ github.event.inputs.nou_contingut_html }}" > index.html

      # Pas 3: Desar els canvis automàticament al repositori
      - name: Fer commit dels canvis
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Actualització automàtica de la web'
          # No cal especificar el token aquí, l'acció el fa servir automàticament
          # si té els permisos correctes, que ja li hem donat al PAT.
